source ~/.sys_profile

# use rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# use nvm
source $(brew --prefix nvm)/nvm.sh
export NVM_DIR=~/.nvm
nvm use default

# use npm mirror
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"